### ISSUE TITLE
Implement Default for Vectors/Matrices/etc.

### ISSUE THREAD

**Issue by Maxjen** [bjz/cgmath#312]
So that users can derive Default for structs that contain them.

**Comment by bjz** [comment]
What would be `Default`? I'm guessing for vectors `zero`, but what about matrices? `zero` or `identity`?

**Comment by Maxjen** [comment]
Good question. I would say probably identity for matrices, but it isn't clear-cut so I guess it might just make more sense to leave it as it is. I hadn't thought of that, sorry.

**Comment by bjz** [comment]
Yeah, it's a tricky question. I've never really been a fan of `Default`, because as a trait it doesn't really bring together any common semantics between types. I'm perfectly cool with having one-off `default` associated functions where it makes sense, but deriving it seems a bit of an anti-pattern.

**Comment by bjz** [comment]
That said, I might be in the minority, and if there is clear guidelines for implementing `Default`, I'm open to being convinced for the sake of downstream crates.
